### ISSUE TITLE
The merge in DAppNode

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#456]
* Running execution client is mandatory. Infura is not allowed:
* Can dappnode provide an eth1 node with the jwt hardcoded to users running out of space?
* Add as mandatory the fee recipient :white_check_mark: 
* We want to add the feature of add a different fee recipient address for every Keystore in the web3signer UI. Blocker: clients must follow the standard https://ethereum.github.io/keymanager-APIs/#/Fee%20Recipient
* Set up every ethereum 1.x and 2.x clients with the correspondent flags by default for validating: JWT token, auth flags, enable API engine

Sources:
https://docs.prylabs.network/docs/prepare-for-merge/
https://ethereum.github.io/keymanager-APIs/#/Fee%20Recipient

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380355002) by [Unito](https://www.unito.io)

**Comment by pablomendezroyo** [comment]
# UPDATE

## Context

With the upcoming merge, DAppNode must adapt itself to the necessities of the validators. The following points must be addressed:

- 1 EL can only receive the [fork choice updated](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#engine_forkchoiceupdatedv1) from 1 CL at a time, otherwise, the behaviour is unexpected and CL does not ensure this would work as expected.
- The checkpointsync is gaining importance due to the weak subjectivity attack on the network. It is highly recommended to be used.
- There are too many configurations that DAppNode users need to do to validate in either prater gnosis and mainnet. With the merge it will be even more complex.

## Tasks

- [ ] Have a dedicated UI for validators in the dappmanager
- [ ] DAppNode must provide a checkpoint sync endpoint @tropicar 
- [ ] In CL DAppNode packages, the checkpoint sync variable should be recommended to be used and it must have as a default value the DAppNode's checkpointsync value @3alpha

**Comment by 3alpha** [comment]
@pablomendezroyo Can we close this now? :)

**Comment by pablomendezroyo** [comment]
Not yet, still pending:
- [ ] Add consensus client to Eth repository core functionality in the dappmanager: https://github.com/dappnode/DNP_DAPPMANAGER/pull/1153

**Comment by pablomendezroyo** [comment]
Done!
