### ISSUE TITLE
Add header to the request from the Prater Beacon Chains to the EL clients

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNode#468]
Details in dappnode/DAppNode#461 

- [ ] dappnode/DAppNodePackage-prysm-prater#89
- [ ] dappnode/DAppNodePackage-lighthouse-prater#64
- [ ] dappnode/DAppNodePackage-teku-prater#77
- [ ] dappnode/DAppNodePackage-nimbus-prater#34
